### PR TITLE
Remove plugins, begin effort to polish phoenix

### PR DESCRIPTION
**Pull request by pfraze**
it's time to get sbot and phoenix shipped! unfortunately, I think that means giving up on extensibility in phoenix for now

I'm going to continue the ideas in #377 in another ssb application. we can evaluate moving the ideas there into phoenix later, if we want

I also think we should close #374 without merging, and remove the "local" role from sbot so only desktop apps can use sbot (no web apps)

@clehner sorry to deprecate your work!

any objections?

### CODE REVIEW

**Comment by ahdinosaur** [comment]
:+1:

**Comment by clehner** [comment]
> @clehner sorry to deprecate your work!

It's okay, if plugins/extensibility is a worthwhile idea I'm sure we'll revisit it, perhaps in another form.

**Comment by pfraze** [comment]
stay tuned, I may just leave this alone for now

**Comment by pfraze** [comment]
going to go ahead and merge this

**Comment by pfraze** [comment]
this got merged but I screwed up the branch meta with a `git reset`, closing

**Pull request closed without merging**
