### PR TITLE
Data feeds UI experiment

### PR DESCRIPTION
**Pull request by pfraze**
Trying out a more data-centric approach to phoenix

### CODE REVIEW

**Comment by pfraze** [comment]
screen shot 2015-02-12 at 2 04 05 pm

**Comment by pfraze** [comment]
screen shot 2015-02-12 at 3 59 14 pm

**Comment by pfraze** [comment]
screen shot 2015-02-13 at 12 44 21 pm

**Comment by pfraze** [comment]
screen shot 2015-02-13 at 8 44 37 pm

**Comment by pfraze** [comment]
screen shot 2015-02-13 at 9 45 13 pm

**Comment by pfraze** [comment]
screen shot 2015-02-14 at 12 02 34 am

**Comment by pfraze** [comment]
screen shot 2015-02-15 at 5 49 18 pm

**Comment by dominictarr** [comment]
that one looks really good.

**Comment by ahdinosaur** [comment]
love the data-centric direction :pear:

**Comment by ralphtheninja** [comment]
Badass! :metal:

**Comment by pfraze** [comment]
screen shot 2015-02-16 at 7 59 44 pm

**Comment by pfraze** [comment]
transitioning to a stronger aesthetic

**Comment by dominictarr** [comment]
hmm, I notice you are flattening the threading?

**Comment by pfraze** [comment]
temporarily

**Comment by pfraze** [comment]
screen shot 2015-02-16 at 10 03 30 pm

**Comment by pfraze** [comment]
screen shot 2015-02-16 at 11 12 44 pm
screen shot 2015-02-16 at 11 12 56 pm

**Comment by pfraze** [comment]
I tried using indentation for the trees but didnt love it -- stashed for now
screen shot 2015-02-16 at 11 52 30 pm

**Comment by pfraze** [comment]
not going to use this, but I liked the semi-3d effect

screen shot 2015-02-17 at 12 19 45 am

**Comment by pfraze** [comment]
Trying a new direction in https://github.com/ssbc/phoenix/tree/datafeeds-unify

screen shot 2015-02-17 at 8 04 20 pm

**Comment by pfraze** [comment]
screen shot 2015-02-17 at 11 16 20 pm

**Comment by pfraze** [comment]
screen shot 2015-02-17 at 11 33 50 pm

**Comment by pfraze** [comment]
screen shot 2015-02-17 at 11 53 13 pm

**Comment by jrf0110** [comment]
I think the large color blocks + large-ish icons are a bit much. You could probably away with just an icon that doesn't interrupt your color scheme kinda like how github does it:

screen shot 2015-02-18 at 11 27 13 am

Just bring it back a notch

**Comment by pfraze** [comment]
This from the guy who criticized us for looking like a bootstrap site!

I'm going to try out some aesthetic concepts that may or may not stick. Aesthetics are holistic so nothing is certain until all the elements are there.

**Comment by jrf0110** [comment]
Oh yeah, I will still criticize the _shit_ out of that aspect. However, one thing at a time :)

**Comment by jrf0110** [comment]
You really do need to fix the whole, "this look like a bootstrap site" thing

**Comment by jrf0110** [comment]
I hope this wasn't sounding too abrasive! I like the layouts and general ideas and such - I'm just bringing suggestions to the table.

I also like how Hipchat does its feeds when labeling items with color:

screen shot 2015-02-18 at 11 52 25 am

**Comment by jrf0110** [comment]
The Feed Item itself having a subtle background and overall theme change, and the left-border both adds continuity between items and indicates the feed item label or type

**Comment by pfraze** [comment]
Yeah, that is nice.

**Comment by pfraze** [comment]
pretty raw
screen shot 2015-02-18 at 10 54 54 pm

**Comment by kumavis** [comment]
i wish there was some low-effort interaction for digging down comment trees, maybe like :hover over a sweet spot. too noisy? too much motion? wouldn't solve the problem of deep comments getting pyramid'd into space.

**Comment by kumavis** [comment]
maybe keyboard navigation is even more 'low effort'

**Comment by dominictarr** [comment]
+1 keyboard

**Comment by pfraze** [comment]
agreed, i'll look for ways to do that

**Comment by pfraze** [comment]
making progress on threads


screen shot 2015-02-20 at 5 17 41 pm

**Comment by pfraze** [comment]
removed chrome

screen shot 2015-02-20 at 6 34 02 pm

**Comment by pfraze** [comment]
updated the compose form

screen shot 2015-02-20 at 8 27 04 pm
screen shot 2015-02-20 at 8 26 49 pm

**Comment by pfraze** [comment]
restyle the left nav

screen shot 2015-02-20 at 9 25 15 pm

**Comment by dominictarr** [comment]
This looks like one that would be easy to fit to mobile too,

**Comment by pfraze** [comment]
almost ready to land

screen shot 2015-02-21 at 12 39 34 pm
screen shot 2015-02-21 at 12 40 14 pm
screen shot 2015-02-21 at 12 40 18 pm

**Comment by pfraze** [comment]
added a fairly simple search algorithm. a query filters messages in the feed such that one query word must match the author nickname, msg type, or text of a post

screen shot 2015-02-21 at 1 27 36 pm

**Comment by pfraze** [comment]
screen shot 2015-02-21 at 2 35 14 pm
screen shot 2015-02-21 at 2 35 18 pm

**Comment by pfraze** [comment]
@dominictarr this is still WIP but it's stable enough to use. Do you want to try it before I merge?

**Comment by pfraze** [comment]
Merging...

**Comment by pfraze** [comment]
published `3.0.0`

**Comment by jrf0110** [comment]
Just did some playing around with the navbar if anyone likies :)
sidebar-theme

**Comment by ralphtheninja** [comment]
@jrf0110 :+1:

**Comment by pfraze** [comment]
Yeah, I like what john did. The reason the dark left nav was removed was that it didnt look great with the thread page, which is visually much lighter than the feed page. I'm going to see how that develops and use john's suggestion if it fits better in the future.

**Pull request merged**
