### PR TITLE
add post attachments 

### PR DESCRIPTION
**Pull request by pfraze**
screen shot 2015-01-19 at 2 55 23 pm
---
screen shot 2015-01-19 at 2 55 37 pm
---
screen shot 2015-01-19 at 2 55 52 pm

### CODE REVIEW

**Comment by dominictarr** [comment]
yes yes yes

**Comment by pfraze** [comment]
screen shot 2015-01-19 at 5 39 05 pm

**Comment by pfraze** [comment]
screen shot 2015-01-19 at 7 15 30 pm
---
screen shot 2015-01-19 at 7 15 47 pm

**Comment by pfraze** [comment]
screen shot 2015-01-19 at 8 50 53 pm

**Comment by pfraze** [comment]
screen shot 2015-01-19 at 8 51 38 pm

**Comment by pfraze** [comment]
screen shot 2015-01-19 at 9 23 53 pm
screen shot 2015-01-19 at 9 25 21 pm

**Comment by kumavis** [comment]
mmmm dat monospace :monorail:

**Comment by pfraze** [comment]
screen shot 2015-01-19 at 11 41 37 pm

**Comment by pfraze** [comment]
this is ready to merge, though still lots to build on attachments

**Comment by pfraze** [comment]
published `2.2.0`

**Pull request merged**
