### PR TITLE
profile pages now show follow, trust, and flag relations

### PR DESCRIPTION
**Pull request by pfraze**
screen shot 2015-01-20 at 2 15 39 pm
screen shot 2015-01-20 at 2 15 54 pm

### CODE REVIEW

**Comment by pfraze** [comment]
any suggestions for presenting this data more cleanly? it's a bit cluttered atm

**Comment by kumavis** [comment]
maybe it should also go on the right?
maybe show 3 random followed/followers, preferring mutual follows, with an expand btn to see the rest

**Comment by kumavis** [comment]
I think given names can be compressed too, to overlap

**Comment by pfraze** [comment]
yeah that's probably a good idea, thank

**Comment by pfraze** [comment]
s

**Comment by pfraze** [comment]
screen shot 2015-01-20 at 2 30 20 pm

**Comment by pfraze** [comment]
published `2.2.2`

**Pull request merged**
