### PR TITLE
Phoenix API refactor - needed updates, notifications, and durable storage

### PR DESCRIPTION
**Pull request by pfraze**
This PR is going to track alongside https://github.com/ssbc/phoenix-api/pull/13

In addition to making necessary updates to phoenix-api, this PR is going to
 1. Fix the "unread messages count" on the inbox
 2. Move any code which uses indexeddb into `phoenix-api` where it may instead use sbot's leveldb instance (rationale explained here: https://github.com/ssbc/phoenix/issues/333)

### CODE REVIEW

**Comment by pfraze** [comment]
Cleaned up the unread and subscribed msg gui elements. An unread message has a down-arrow. A subscribed message has a star.

screen shot 2015-02-25 at 9 21 34 pm

**Comment by pfraze** [comment]
Still trying to nail the read/unread/subscribed indicator. The icons were simpler and less intrusive, but they required you to look away from the content of the message. I'm trying colored bars now instead. Gold indicates subscribed and dark gray indicates unread.

screen shot 2015-02-26 at 2 30 58 pm

Still not sure we need subscribed threads to be highlighted, though.

**Comment by dominictarr** [comment]
@pfraze how do you subscribe to a feed?

**Comment by pfraze** [comment]
@dominictarr you mean, to a message? It happens automatically to your posts, and there's also a button at the bottom of the thread page for controlling it -- but I'm not happy with that button yet.

**Comment by pfraze** [comment]
moved the bands over to the left and let the "unread" color be a variation of whatever color its row already used

screen shot 2015-02-26 at 6 53 29 pm
screen shot 2015-02-26 at 6 53 38 pm

inbox unread count is now correct as well, so this should be good to go. going to merge soon

**Comment by pfraze** [comment]
right now, the unread items are visually heavier. Should it be the reverse?

**Pull request merged**
