### PR TITLE
User / social tools: profile pics, "app" users, etc

### PR DESCRIPTION
**Pull request by pfraze**
Working on tools for other users, adding profile pics, "app" users, etc

### CODE REVIEW

**Comment by pfraze** [comment]
screen shot 2015-03-07 at 1 54 24 pm

**Comment by pfraze** [comment]
Profile pics are now in a working state, including a image uploader that lets you crop, resize, and set a background color for outside space
screen shot 2015-03-08 at 11 11 01 pm
screen shot 2015-03-08 at 11 11 03 pm
screen shot 2015-03-08 at 11 12 45 pm

**Comment by dominictarr** [comment]
looks like a real social app now!

**Comment by pfraze** [comment]
notifications ui Im trying out for aliasing apps
screen shot 2015-03-10 at 8 34 19 pm

**Comment by pfraze** [comment]
screen shot 2015-03-11 at 10 37 27 pm
screen shot 2015-03-11 at 10 47 45 pm

**Comment by pfraze** [comment]
https://github.com/ssbc/phoenix/issues/340#issuecomment-78395335

**Comment by pfraze** [comment]
there was a compile error during publish, corrected build published `4.1.1`

**Pull request merged**
