### PR TITLE
Internet points

### PR DESCRIPTION
**Pull request by pfraze**
Adding stats to the UI, things like reply count, up/down votes (see #350), follower counts, etc

### CODE REVIEW

**Comment by pfraze** [comment]
screen shot 2015-03-17 at 8 00 04 pm
screen shot 2015-03-17 at 8 00 16 pm

**Comment by pfraze** [comment]
decided to go with something more fun than arrows - stars and fires

screen shot 2015-03-17 at 8 46 50 pm

**Comment by pfraze** [comment]
star/fire wont work, but was fun to try. back to up/down arrows

**Comment by pfraze** [comment]
implemented in threads now as well

screen shot 2015-03-17 at 11 57 24 pm

mostly done, now if we decide to go forward with this, I'll need to factor some of the code out into `ssb-message-schemas`

**Comment by kumavis** [comment]
haven't checked in for a bit -- looking slick!

**Comment by pfraze** [comment]
@kumavis thanks!

new feature, can now see who voted in the thread view
screen shot 2015-03-19 at 5 27 05 pm

**Comment by pfraze** [comment]
starting on a new design for the profile pages that tries to help you evaluate user reputation/trust more easily, including with up/down voting profiles

screen shot 2015-03-20 at 2 03 51 pm

**Comment by pfraze** [comment]
improved the totem rendering to derive from the palette of the profpic

screen shot 2015-03-20 at 2 41 27 pm
screen shot 2015-03-20 at 2 41 43 pm
screen shot 2015-03-20 at 2 41 54 pm

**Comment by pfraze** [comment]
more tweaks

screen shot 2015-03-20 at 3 13 46 pm

**Comment by pfraze** [comment]
add subpage nav btns
screen shot 2015-03-20 at 5 33 16 pm

**Comment by kumavis** [comment]
nice! trimmed the top right? looks off balance but maybe alright

**Comment by pfraze** [comment]
yeah it's all WIP

**Comment by pfraze** [comment]
wasnt happy with those subnavs so tried a million things, ultimately decided to make the profile page take you to info about the user and tell you it does that with an overlay:

screen shot 2015-03-20 at 7 09 03 pm

**Comment by pfraze** [comment]
ok, for the last bit of ui functionality on this PR, up/down voting on profiles:

screen shot 2015-03-22 at 11 50 57 am
screen shot 2015-03-22 at 11 51 02 am

**Comment by pfraze** [comment]
@dominictarr ok this is ready to discuss, and if we move forward I'll factor out some code into `ssb-msg-schemas` and possibly into `phoenix-api` and then we can merge. (I still want to tweak some visuals on this sidebar though, not 100% satisfied with the colors.)

This PR adds up/down voting to all messages and to users' profiles. It strips the profile sidebar down to the follows, votes, and voters. The next PR will add a second view of the profile for the more detailed information that I removed-- everything to do with the contact messages and also discussion about the up/down votes.

Part of the idea I'm proposing here is to replace the trust/flag buttons with the up/down votes for evaluating trust. The reason I propose this is for ease-of-understanding; I think people will intuitively understand up/down voting, even though it's less specific than trust/flag. The votes will be commentable (like any message, it can have a thread) and so people can discuss why they've voted one way or another, and that becomes a simple way to evaluate trust in someone. (We might consider a popup on downvote which lets you choose "spammer / troll / fake / etc.")

Up/down votes are less specific than trust/flag, and so people may downvote for non-security reasons (that ho stole five dollars!). It could get very petty. I think that's the nature of a social system, but I'm open to discussing the repercussions of this.

The trust btn had another purpose, which was to use the names by that person. My next PR is going to tackle that. I want to try a few things and see if there are other approaches I want to propose. if not, I'll re-implement the trust btn then

**Comment by kumavis** [comment]
@pfraze are you doing color detection on the photos?

**Comment by pfraze** [comment]
@kumavis yep

**Comment by kumavis** [comment]
:cool:

**Comment by kumavis** [comment]
Did you write it? Looking in the package.json for this branch, didn't see anything seemingly relevant. If so please publish! cool stuff

**Comment by pfraze** [comment]
stole it from stackoverflow but it's very simple, https://github.com/ssbc/phoenix/blob/internet-points/src/lib/util.js#L73 just this guy right here. Draw on canvas, get image data, average the RGB of a pixel sample.

**Comment by dominictarr** [comment]
@pfraze lets do it!

**Comment by pfraze** [comment]
:guitar: merging

**Comment by pfraze** [comment]
oh shoot I got excited and forgot I had more work, going to open another PR and will publish when that's done

**Pull request merged**
