### PR TITLE
Simplify: reduce the phoenix featureset

### PR DESCRIPTION
**Pull request by pfraze**
I'd like to reduce phoenix to its bare essentials.
The interesting things should happen in userland.
If phoenix is simpler, it'll be easier to generalize and to maintain.

This PR is a proposal. If anybody feels these features need to stay builtin, feel free to say so.

### CODE REVIEW

**Comment by pfraze** [comment]
Reduce the feed page to its most basic view - all content. Remove the inbox entirely.

screen shot 2015-04-13 at 1 27 19 pm

**Comment by pfraze** [comment]
@clehner @ahdinosaur @dominictarr are yall ok with this change? or would you rather the features stay in core?

**Comment by clehner** [comment]
It looks good, but how will users learn about activity mentioning them, without the inbox? Will they have to scan the feed to find mentions?

**Comment by ahdinosaur** [comment]
i'm reminded of Alan Kay on [how the web browser should be more like an OS kernel than an app](https://youtu.be/FvmTSpJU-Xc?t=20m20s). ([xposted on ssb](http://localhost:2000/#/msg/YRUHw9g/k6dSXPjStjoc5r6vtE0IlhPC/HigHPNAfmY=.blake2s))

i think there's a few directions for phoenix:
1. try to be a sweet mass-market discussion app
2. try to be a sweet raw message app for ssb developers
3. try to be a sweet generalized platform for hosting ssb apps

as a potential ssb app developer, i'm most skeptical of 3, as i might be bringing existing codebases into the ecosystem that already have some opinions and can at best slowly transition. that being said, a generalized app platform would be amazing for new apps who want to start on ssb and existing apps who have transitioned, but i'd rather see that happen as progressive iteration towards 2.

@pfraze what direction (not necessarily limited to my 3 or only 1) are you interested in for Phoenix?

**Comment by pfraze** [comment]
@clehner my thinking is that a plugin will take over that job. 

 - On the one hand,
  - it'll take some time for that to happen, so we'll be losing the feature in the short term.
  - It's also possible that a plugin won't able to do it as well as phoenix can (we may come to find). 
 - On the other hand, 
  - phoenix's inbox needs work, and simplifying would help focus on plugins.

Of course, there's no harm in leaving it as-is in the meantime either. It *is* handy.

@ahdinosaur a good question

Whatever we do with phoenix, ssb & sbot will support an ecosystem of other external apps. That hasn't happened yet because we haven't been able to decide on a security regime (#349). As a matter of fact, it's possible to create apps now which read `~/.ssb/private` and connect to sbot with master rights -- we just haven't publicized that much. Perhaps we will soon.

With the recent update to include injected plugins, the idea became, "well, maybe we can focus on audibility instead of permissions." SSB is suited to auditing because of signed authorship and content-addressing. And so that shifted our interest to the package manager and, more broadly, to distribution via SSB itself.

So what's the vision here? Let me refer to [this interview with Torvalds about Git](http://www.linux.com/news/featured-blogs/185-jennifer-cloer/821541-10-years-of-git-an-interview-with-git-creator-linus-torvalds).

> The big thing about distributed source control is that it makes one of the main issues with SCM's go away - the politics around "who can make changes." BK showed that you can avoid that by just giving everybody their own source repository.

The effect that git had as a distributed scm, I believe ssb can have as a distributed web service -- a solution to the political problem around "who can make changes." This extends to a right to determine your software as a community, and a right to self-governance. Society, not social network.

What is phoenix's minimal role in this process? Our basic needs are:

 - To review the feed
 - To have discussions
 - To discover and evaluate users
 - To deploy software packages
 - To audit the packages
 - To execute the packages

The crucial question is, how will we choose to execute the packages? because it will determine how Phoenix is constructed. 
 - If we want to go forward with user plugins, then Phoenix should be something of a shell environment, and focus mainly on assisting userland. (This is the mentality of this PR.)
 - If we instead would like to use node as the execution environment, or have packages be SPAs which phoenix hosts, we can do that, and focus Phoenix around the other 5 goals.

@ahdinosaur I share your skepticism about creating a new ecosystem. @clehner As potential app developers, what do you think you'd get the most enjoyment and value from?

**Comment by clehner** [comment]
I like the idea of a distributed platform for communication and collaboration. I think that spinning off parts of Phoenix into plugins is a good idea. I could imagine Phoenix eventually hosting itself on SSB, assuming a capable package manager (#364). I'm most interested in client-side plugins, but I can see server-side plugins being useful too (e.g. torrent tracker, ipfs integration).

As for this PR, while seeing mentions or relevant posts supports our basic needs of e.g. having discussions, if simplifying the feed page gives us room to create better solutions for this, then I think it's a good idea.

**Comment by dominictarr** [comment]
I think this is an direction worth exploring... although I think that inbox is pretty fundamental... or rather, notifications are... you need to know what that a thing (document/thread) has changed since you last saw it.

**Comment by pfraze** [comment]
Ok, I'm thinking this PR shouldn't merge yet, but we should keep evaluating it as we go.

Spun this discussion off into #370

**Comment by pfraze** [comment]
After some discussion, we're probably not going to focus on extensibility in the nearterm, so I'm going to close this.

**Pull request closed without merging**
