### PR TITLE
more design work

### PR DESCRIPTION
**Pull request by pfraze**
continuing the design tweaking

### CODE REVIEW

**Comment by pfraze** [comment]
committed this to a side branch because Im not sure of it, but here's a quick shot at the hermit-crab mascot

screen shot 2015-03-15 at 3 18 33 pm
screen shot 2015-03-15 at 3 18 39 pm

**Comment by pfraze** [comment]
here's how we can get some hexagrids in action
screen shot 2015-03-15 at 4 16 46 pm

**Comment by pfraze** [comment]
gave some attention to the right nav

screen shot 2015-03-15 at 5 12 31 pm

**Comment by pfraze** [comment]
darken the header ctrls

screen shot 2015-03-15 at 5 31 42 pm

**Comment by pfraze** [comment]
things were just getting way too contrasty, so I lightened up the right column and the header. Much nicer, imo!

screen shot 2015-03-15 at 6 09 46 pm

**Comment by pfraze** [comment]
per @jrf0110's suggestion, tweaked the left nav a bit

screen shot 2015-03-15 at 6 26 21 pm

**Comment by pfraze** [comment]
hexafied the addressbook

screen shot 2015-03-15 at 6 21 38 pm

**Comment by ralphtheninja** [comment]
:+1:

**Comment by pfraze** [comment]
updated threads

screen shot 2015-03-15 at 7 21 17 pm

**Comment by pfraze** [comment]
ok this guy's pretty fat by now, going to merge it on in

**Comment by pfraze** [comment]
published `4.3.1`

**Pull request merged**
