### PR TITLE
visual indication of bad @-mentions

### PR DESCRIPTION
**Pull request by pfraze**
screen shot 2015-01-18 at 3 29 07 pm

### CODE REVIEW

**Comment by pfraze** [comment]
published `2.1.1`

**Comment by dominictarr** [comment]
what sort of "bad" is this?

**Comment by pfraze** [comment]
it doesnt actually map to a known name

@dfsafdasdfasdfasdf <-- thats how github handles the same issue

**Comment by pfraze** [comment]
to be more specific, it doesnt map to a known name at the time of posting. when you post, the name gets replaced by the full id, and then subsequent rendering shows the local user's name for the user

**Comment by dominictarr** [comment]
oh okay cool

**Pull request merged**
