### PR TITLE
Another round of ux polish

### PR DESCRIPTION
**Pull request by pfraze**
:racehorse: :arrow_right: :checkered_flag:

### CODE REVIEW

**Comment by pfraze** [comment]
lightened the nav, made the ui much lighter overall

**Comment by pfraze** [comment]
moved the nav to the top of the page, put the composer as an inline control at the top of the feed

screen shot 2015-04-22 at 9 49 55 pm

**Comment by clehner** [comment]
Nice!

**Comment by pfraze** [comment]
I was planning to do in-place expansion of feed messages into their threads (on click) but then realized it would be much easier as a modal. Normally I'm anti modal, but I think this could work pretty well. Here's the first pass at it:

thread-modals

**Comment by pfraze** [comment]
updated address book:

screen shot 2015-04-24 at 1 16 41 pm
screen shot 2015-04-24 at 1 16 39 pm

**Comment by pfraze** [comment]
updated the profile page

screen shot 2015-04-24 at 1 29 33 pm

**Comment by pfraze** [comment]
restyled threads a bit

thread-restyles

**Comment by pfraze** [comment]
merging

**Comment by pfraze** [comment]
published `4.5.5`

**Pull request merged**
