### PR TITLE
User programs

### PR DESCRIPTION
**Pull request by pfraze**
Per #361

### CODE REVIEW

**Comment by pfraze** [comment]
started things out by removing ads and making some UI simplifications that I've been intending to make

screen shot 2015-04-02 at 5 14 44 pm

I removed ads because they need more work to make sense, and it's the kind of feature that I want user programs to handle

now going to get started on user-program features

**Comment by ahdinosaur** [comment]
+1 on removing ads.

**Comment by pfraze** [comment]
@dominictarr what do you figure the message schema should include for a posted program?

Where I'm at: in the UI, I'm calling these "programs." I just like that word. Alternatives: modules, addons, plugins, scripts.

I'm keeping them as unstructured as possible right now. On execute, it'll eval the script in a strict-mode closure. If you want to script to eval on load, that'll be a toggle option. Phoenix will expose a global object, `phoenix`, to give access to the APIs that phoenix itself uses.

We can do an app-specific schema here (`type: phoenix-program`) but I'm inclined to try a generalized schema first (`type: program`).

With that in mind, here are the data I can imagine wanting in the schema:

 - Name
 - Semantic version
 - Description
 - Link to the code blob
 - Link(s) to screenshots
 - Link to the previous version published
 - Platform name (eg `phoenix`, `node`) and semantic version

And then there's plenty of stuff that can go in other messages -- votes up/down, tags/categories, audits, etc.

We don't need to make any hard decisions, just want to start the conversation now while I experiment. Thoughts?

**Comment by dominictarr** [comment]
@pfraze there is kinda a pattern developing for mutable documents,
`root` link to first initial version, `branch` link(s) to immediately previous versions.

semver would be easy, but I think using `patches` `addsFeature` and `breaks` links would be more fork friendly. (or "fixes", "extends", "breaks"?). straight semver would work if there was only one author, but easily have version name collisions with multiple authors.

With a single author it would be easy to compute what the version number would be.

I'd lean towards putting the sceenshots etc in a separate document, since it's just documentation, it's like any other page.

**Comment by ahdinosaur** [comment]
it seems like we're building a distributed npm, which is really great, but then maybe we should focus on that and forget eval'ing the modules in phoenix (which i'm much less excited about).

**Comment by dominictarr** [comment]
@ahdinosaur we know eval is a bad idea, but it's only temporary and we'll replace that with something better later. To make eval remotely safe we need a good auditing flow, which is what this current exploration will lead us toward I hope.

**Comment by dominictarr** [comment]
@ahdinosaur I'm certainly still looking at a strict permissions system, but that has other dependencies (refactoring networking, and changing authorization)

**Comment by ahdinosaur** [comment]
makes sense, carry on with what you think is best and i'm happy to be part of the experiment. :microscope: :rat:

**Comment by pfraze** [comment]
@ahdinosaur do you think there's a way we could structure this package-system such that it supports more platforms than just phoenix-eval? That's my thinking with the platform information -- that maybe it could also distribute node modules and unix programs and etc, in time. Or, if not with these exact message types, we can learn the patterns here to then extend into other platforms.

In the meantime, I've got big ideas for the eval! I'm hoping it'll be much neater than it might sound. (And, by the way, thanks for being so supportive! You guys really make this a fun project.)

@dominictarr yeah that's a neat idea, the patches/addsFeature/breaks links. I was trying not to do anything novel yet, but I think that's a really logical choice.

If we put screenshots in another message, maybe we should move description out as well?

**Comment by ahdinosaur** [comment]
@pfraze idk, but luckily package managers have some history. for reference off the top of my head:

- [npm packages](https://docs.npmjs.com/files/package.json)
- [debian packages](https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html)
- [arch linux packages](https://wiki.archlinux.org/index.php/PKGBUILD)
- [gentoo packages](https://wiki.gentoo.org/wiki/Repository_format/package/Manifest)

i'm skeptical about a platform field, seems like something better served by a `#!` or something like it, but still idk.

**Comment by pfraze** [comment]
@ahdinosaur good links, I'll give them a read.

Platform isn't be the right solution, you're right. Now that I think about it, I'd use that data for categorization, in which case it just needs to be tagged (or whatever).

Keep the input coming.

**Comment by pfraze** [comment]
This is what I'm thinking about for the script definitions: https://gist.github.com/pfraze/4c0e3c2c37e7165a8023

**Comment by pfraze** [comment]
working on the program editor

screen shot 2015-04-04 at 3 39 41 pm

**Comment by dominictarr** [comment]
@pfraze can you write an intro for https://gist.github.com/pfraze/4c0e3c2c37e7165a8023 it's hard to jump into code without any context

**Comment by pfraze** [comment]
@dominictarr --

The details may/will change.

I'm modeling the execution model vaguely after node's. The scripts are programs. If they register any long-living functions or objects, those will persist until removed by phoenix.

The phoenix global gives APIs to command and modify the app. `phoenix.com()` registers a component which phoenix will integrate into the UI. The types of components I'm considering: pages, widgets, ssb-message handlers. 

A script *could* add behaviors by modifying the DOM or using browser APIs. I don't recommend that. Phoenix's com registry will manage component lifetime and shared resources (like the DOM). 

I'm not considering a modules system yet, but, when we add it, we need to consider the following issues:

 - will it be commonjs style, or do we want to use the es6 syntax?
 - will it integrate into npm?
 - will it integrate into the ssb package manager?
 - how will module dependencies be installed?

**Comment by pfraze** [comment]
actually, this got me to thinking, the new modules system might be a good candidate. we might consider using that instead of eval

Can look into this polyfill: https://github.com/ModuleLoader/es6-module-loader
Or maybe use https://github.com/systemjs/systemjs, which gives lots of support for different module formats

**Comment by pfraze** [comment]
Might even use http://babeljs.io/...

**Comment by pfraze** [comment]
We decided in IRC to use prebundling and defer the runtime modules system. That means we need to be able to use your native stack of tools, like browserify.

Instead of an in-app editor, I'm going to enumerate JS files in a local directory. 

Before that, going to go ahead and merge this PR, since it has some fixes, and start a new one.

**Comment by pfraze** [comment]
published `4.4.3`

**Pull request merged**
