### PR TITLE
blob hosting

### PR DESCRIPTION
**Pull request by pfraze**
add a `/ext/<hash>` route to the server to serve blobs

### CODE REVIEW

**Comment by dominictarr** [comment]
awesome!

what about `content-type`? Would there be problems with just returning it as whatever content type was requested?

**Comment by pfraze** [comment]
the accept header can include a list of content types, eg `png`, `gif`, or `jpg`, so choosing one probably wouldn't work

i'm not really sure what'll happen if we dont have a content type. we may have to add mimetype metadata to the blobs

**Comment by dominictarr** [comment]
probably the place we will put the mime type will be the `ext` link... so the client will know it, but not the blob store, so allowing the client to request a particular mime type is a little strange but not necessarily unreasonable.

**Comment by pfraze** [comment]
good point. we just need to make sure we dont do more harm than good - for instance, if the browser defaults to some accept header for an `` then that'd be a problem

we could also consider doing `/ext/<hash>.<ext>`

i'll test a bit and see what happens if we dont use a content-type header. we could also add `name` attributes to ext links and have a path like `/msg/<msghash>/<ext-name>`

**Comment by dominictarr** [comment]
yup, that sounds good.

**Pull request merged**
