### PR TITLE
User Programs 2: Electric Boogaloo

### PR DESCRIPTION
**Pull request by pfraze**
continuing #361

### CODE REVIEW

**Comment by pfraze** [comment]
Ooooohk, this is actually ready to rock. Gonna put together some example plugins to test and document.

**Comment by No9** [comment]
:+1:

**Comment by pfraze** [comment]
screenshots from the trophies example plugin

screen shot 2015-04-09 at 6 52 21 pm
screen shot 2015-04-09 at 6 52 39 pm

**Comment by pfraze** [comment]
merging

**Comment by pfraze** [comment]
published `4.5.0`

**Pull request merged**
