### PR TITLE
publishing ux experiment

### PR DESCRIPTION
**Pull request by pfraze**
this PR shifts phoenix from a purely discussions/mail approach to a publishing-first approach, with discussions/mail acting beside it.

experimental branch. see https://github.com/ssbc/phoenix/issues/292 for background

---

this PR styles itself after reddit - think "reddit for files." the focus is content publishing and discovery, with discussion threads around the content. published html files can be opened, just as if hosted on the web and linked to by a redditor

(if you're just looking at the screenshots in this PR, start at the bottom for most recent)

### CODE REVIEW

**Comment by pfraze** [comment]
screen shot 2015-01-27 at 4 21 45 pm

trying something reddit-like. this makes the text of the first post a title - replies will remain markdown text.

screen shot 2015-01-27 at 4 25 48 pm

links turn purple

**Comment by pfraze** [comment]
screen shot 2015-01-27 at 5 07 49 pm

updated the thread-view to match the summary-view style

**Comment by pfraze** [comment]
screen shot 2015-01-27 at 5 42 24 pm

more work on the thread view

**Comment by pfraze** [comment]
thinking about how attachments should be put into threads. three types of attachments:

 - `rel=main`. if given, the post's link in the feed view points to this attachment, hosted alone (outside of phoenix)
 - `rel=post-body`. a text/markdown blob which is inlined as the body of the post
 - `rel=attachment`. a generic blob. if an image, a thumbnail is shown under the post

**Comment by pfraze** [comment]
still need...

 - [ ] add "post body" to compose form
 - [ ] add "main file" to compose form
 - [ ] render message attachments (inline images as thumbnails, use icons for others)
 - [ ] use "mail file" link when present as thread's title link
 - [ ] render post-body on message page when present

**Comment by dominictarr** [comment]
Hmm, so, previously we have been using the `rel` as the mime type... was that a bad idea?

Maybe it should be about how it relates to the message... like "embed" or "content" and then have a mime property (remember the entire link object is stored in the index, so it will be possible to get this again easily if we want it)

What is the difference between "main" and "post-body"?

**Comment by pfraze** [comment]
> Hmm, so, previously we have been using the rel as the mime type... was that a bad idea?

no but

> Maybe it should be about how it relates to the message... like "embed" or "content" and then have a mime property (remember the entire link object is stored in the index, so it will be possible to get this again easily if we want it)

after giving it some thought, i felt this way. what i'm doing now is using a `name` field and pulling mimetype from the file extension, which i think should work well enough

> What is the difference between "main" and "post-body"?

"main" is a bit weird - basically, it's the subject of the post. when you click on a link to the post, you go to the main ext. if there is no main, then you go to the discussion thread. (this mimic's reddit's behavior, where you can do posts with links or just textual "self" posts)

"post-body" is a markdown blob that acts as the content of the post. it renders inline on the discussion thread.

i should finish up that checklist today and you'll be able to see what i'm thinking

**Comment by pfraze** [comment]
screen shot 2015-01-28 at 1 33 58 pm

moving more towards publishing files. this interface is pretty uninspired but i just need something that works first

screen shot 2015-01-28 at 1 34 42 pm

**Comment by pfraze** [comment]
some visual tweaks to the compose form

screen shot 2015-01-28 at 3 14 52 pm
screen shot 2015-01-28 at 3 15 40 pm

**Comment by pfraze** [comment]
added attachment thumbnails to threads
screen shot 2015-01-28 at 3 47 45 pm
screen shot 2015-01-28 at 3 48 00 pm

**Comment by pfraze** [comment]
decided to ditch the `rel=post-body` attachment for now, since we can test out this experiment without that
screen shot 2015-01-28 at 4 15 45 pm

**Comment by pfraze** [comment]
might be better to ditch `rel="attachment"` and just do something like `main: true` on the main link

**Comment by pfraze** [comment]
few more tweaks

screen shot 2015-01-28 at 6 41 12 pm

**Comment by dominictarr** [comment]
I'm trying to get this to work, but I'm not seeing any attachments...
and the network page (and scuttlebot log) is complaining that it's not successfully connecting to either mine or your server... hmm, this could just be my current network though.

**Comment by pfraze** [comment]
hm, some suggestions if it's not a network thing --

 - `npm run build` or `sbot server --dev` for phoenix
 - any deps on non-master branches?
 - is it possible one of my deps are on non-branches, and so i checked in bad code?

**Comment by pfraze** [comment]
screen shot 2015-01-28 at 10 07 59 pm
replies render correctly on profile/inbox

**Comment by dominictarr** [comment]
It would probably be more reliable to have a mime type property than to use
the file extension. Extensions are usually abbreviated to 3 letters so
collisions are likely.

We can add more data so we should.

**Comment by pfraze** [comment]
screen shot 2015-01-29 at 10 40 50 am

**Comment by pfraze** [comment]
added post bodies as attachments to toplevel (non-reply) posts. this only applies to toplevels -- replies still put their body-text inside the message itself.

not 100% sure how i feel about this. on the one hand, it gets rid of the size limitation of messages. on the other hand, it requires an extra blob fetch that may be unnecessary. it's also inconsistent with replies, which means it complicates the `post` message schema.

note - at-mentions dont work in the post body yet

screen shot 2015-01-29 at 11 55 54 am
screen shot 2015-01-29 at 12 01 55 pm

**Comment by dominictarr** [comment]
If the post is short it should be in the message...

Maybe if the post is long then there should still be an intro bit that is
in the message... It would default to the first paragraph?

**Comment by pfraze** [comment]
you know.... i've gone off this.

the existing gmail-clone is simple, it works, it does what we need it to.
we need to experiment on the side with apps. for that, we should just use the third-party-domain auth (already built and working). it's very simple, and it avoids the rabbit-hole of decision-making that this PR goes down. i'm going to put my energy there for a bit and see how it feels.

**Pull request closed without merging**
